In [1]:
from pymongo import MongoClient

In [2]:
client = MongoClient("mongodb+srv://daviddeng8:SafetyMaps@crimedata-pebxn.mongodb.net/data?retryWrites=true&w=majority")

In [3]:
db = client.data
collection = db['bigger_and_badder_crime_data']

In [4]:
documents = []
cursor = collection.find({})
for document in cursor:
    documents.append(document)

In [11]:
print(len(documents))
print(documents[0])

18855
{'_id': ObjectId('5ecc6323d6f23b062a7a1e26'), 'id': 2022, 'nodes': [1833121478, 278607482, 1833121479, 1833121480, 1833121482, 1833121483, 1833121484, 1833121485, 1833121486, 1088042086, 1833121488, 1833121489, 1833121490, 1833121492, 1833121493, 1833121495, 278610128, 1088042067, 661549, 1088042108], 'tags': ['bicycle', 'yes', 'hgv', 'designated', 'highway', 'motorway', 'lanes', '2', 'maxspeed', '70 mph', 'name', 'Mojave Freeway', 'oneway', 'yes', 'ref', 'I 15', 'source:maxspeed', 'sign'], 'name': 'Mojave Freeway', 'coords': [[35.0683591, -116.4159934], [35.0730298, -116.4088254], [35.0773911, -116.4021348], [35.0779524, -116.401106], [35.0784058, -116.4000684], [35.0786864, -116.3992066], [35.0789527, -116.3982129], [35.079075, -116.3970962], [35.0791417, -116.389567], [35.079211, -116.3883741], [35.0793818, -116.387442], [35.0795387, -116.3865293], [35.0798987, -116.3853628], [35.0805194, -116.3840312], [35.0826023, -116.3796209], [35.0832107, -116.3777658], [35.0834293, -116.

In [13]:
from sklearn.neighbors import BallTree
import numpy as np

In [22]:
coords = {}
for doc in documents:
    prev = None
    for i,coord in enumerate(doc["coords"]):
        coord_str = str(coord[0]) + "," + str(coord[1])
        if coord_str not in coords:
            coords[coord_str] = {
                "coord": coord,
                "name": doc["name"],
                "crime": doc["dist_from_crime_all_vals"][i],
                "adj": []
            }
        if prev is not None:
            coords[coord_str]["adj"].append(prev)
            coords[prev]["adj"].append(coord_str)
        prev = coord_str

In [25]:
coord_list = []
for k in coords:
    coord_list.append(coords[k]["coord"])
print(len(coord_list))

94330


In [27]:
tree = BallTree(coord_list, metric='haversine')

In [38]:
print(coord_list[0])
print(coord_list[29508])
dist, ind = tree.query([coord_list[0]],k=5)
print(dist)
print(ind)

[35.0683591, -116.4159934]
[35.0684189, -116.416573]
[[0.         0.00050912 0.0029454  0.00433921 0.00437051]]
[[    0 29508 41597 29509 41596]]


In [44]:
print(coord_list[0])
ind = tree.query_radius([coord_list[0]],r=0.01)
print(ind[0])
print(coord_list[29508])

[35.0683591, -116.4159934]
[41596 41597     0 29508 29509     1 29507]
[35.0684189, -116.416573]


In [42]:
def coord_to_str(coord):
    return str(coord[0]) + "," + str(coord[1])

In [80]:
RADIUS = 0.0003

compressed_coords = {}
coord_mapping = {}
processed = set()
for i, coord in enumerate(coord_list):
    #if i % 10000 == 0:
    #    print("Completed processing " + str(i) + " entries!")
    coord_str = coord_to_str(coord)
    if i in processed:
        continue
    processed.add(i)
    coord_mapping[coord_str] = coord_str
    cdata = {
        "coord": coord,
        "name": coords[coord_str]["name"],
        "crime": coords[coord_str]["crime"],
        #"adj": coords[coord_str]["adj"][:],
        "adj": set(),
        "pts": 1
    }
    ind = tree.query_radius([coord], r=RADIUS)
    for k in ind[0]:
        if k > i:
            processed.add(k)
            coord_mapping[coord_to_str(coord_list[k])] = coord_str
           # objdata = coords[coord_to_str(coord_list[i])]
            cdata["crime"] = (cdata["crime"] * cdata["pts"]+ coords[coord_to_str(coord_list[i])]["crime"])/(cdata["pts"]+1)
            cdata["pts"] += 1
           # for adj in objdata["adj"]:
           #     if adj not in cdata["adj"]:
           #         cdata["adj"].append(adj)
    compressed_coords[coord_str] = cdata

print("Original length", len(coords.keys()))
print("Compressed length", len(compressed_coords.keys()))
            

Original length 94330
Compressed length 41698


In [81]:
for cstr in coords:
    csm = coord_mapping[cstr]
    adjset = compressed_coords[csm]["adj"]
    for c in coords[cstr]["adj"]:
        cm = coord_mapping[c]
        if cm not in adjset and cm != csm:
            adjset.add(cm)

In [82]:
avg = 0.0
for coord in coords:
    for a in coords[coord]["adj"]:
        avg += 1
        
avg /= len(coords.keys())
print("Old average connections per coord", avg)

avg = 0.0
for coord in compressed_coords:
    for a in compressed_coords[coord]["adj"]:
        avg += 1
        
avg /= len(compressed_coords.keys())
print("New average connections per coord", avg)

Old average connections per coord 2.062715997031697
New average connections per coord 2.290277711161207


In [83]:
for k in compressed_coords:
    print(compressed_coords[k])
    break

{'coord': [35.0683591, -116.4159934], 'name': 'Mojave Freeway', 'crime': 0.3239299542413419, 'adj': {'35.0665814,-116.4186842', '35.0730298,-116.4088254'}, 'pts': 1}


In [84]:
docList = []
for k in compressed_coords:
    adjList = []
    for a in compressed_coords[k]["adj"]:
        adjList.append(a)
    docList.append({
        "coord": compressed_coords[k]["coord"],
        "coord_str": coord_to_str(compressed_coords[k]["coord"]),
        "name": compressed_coords[k]["name"],
        "crime": compressed_coords[k]["crime"],
        "adj": adjList,
    })
    
print(docList[0])

{'coord': [35.0683591, -116.4159934], 'coord_str': '35.0683591,-116.4159934', 'name': 'Mojave Freeway', 'crime': 0.3239299542413419, 'adj': ['35.0665814,-116.4186842', '35.0730298,-116.4088254']}


In [85]:
saveto = db['compression_test3']
saveto.insert_many(docList)
    